# Generated by Django 4.2 on 2024-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productvariant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
